/** Auto-generated by scripts/write-ox-update-manifest.mjs — do not edit. */
export const OX_NATIVE_VERSION = "0.3.6";
export const OX_NATIVE_BUILD_NUMBER = 14;
export const OX_RUNTIME_VERSION = "2026.09.30.1";
export const OX_RELEASE_ID = "ox-20260930-49c523f862";
export const OX_RUNTIME_URL = "https://xperience.getlifeos.app";
