/** Auto-generated by scripts/write-ox-update-manifest.mjs — do not edit. */
export const OX_NATIVE_VERSION = "0.3.4";
export const OX_NATIVE_BUILD_NUMBER = 12;
export const OX_RUNTIME_VERSION = "2026.09.21.3";
export const OX_RELEASE_ID = "ox-20260921-adec488d7b";
export const OX_RUNTIME_URL = "https://xperience.getlifeos.app";
