/** Auto-generated by scripts/write-ox-update-manifest.mjs — do not edit. */
export const OX_NATIVE_VERSION = "0.3.5";
export const OX_NATIVE_BUILD_NUMBER = 13;
export const OX_RUNTIME_VERSION = "2026.09.29.1";
export const OX_RELEASE_ID = "ox-20260929-2297d207df";
export const OX_RUNTIME_URL = "https://xperience.getlifeos.app";
