import { reviewTransitionAllowed, validateManifest, type ApplicationManifestClaim, type EvidenceType, type ReviewState } from "@digiconomy/xperience-contract";
export type Role = "DEVELOPER" | "ADMIN";
export interface Actor { id: string; role: Role; }
export interface Application { id:string; developerId:string; state:ReviewState; manifest:ApplicationManifestClaim; revision:number; }
export interface AuditEvent { action:string; actorId:string; applicationId:string; at:string; detail?:string; }
export class XperienceService {
  private apps = new Map<string, Application>(); readonly audit: AuditEvent[]=[];
  register(actor:Actor, manifestInput:unknown): Application { if(actor.role!=="DEVELOPER") throw new Error("Developer role required."); const valid=validateManifest(manifestInput); if(!valid.ok) throw new Error(valid.errors.join(" ")); if([...this.apps.values()].some(a=>a.manifest.origin===valid.value.origin)) throw new Error("Application origin already registered."); const app={id:valid.value.applicationId,developerId:actor.id,state:"DRAFT" as const,manifest:valid.value,revision:1}; this.apps.set(app.id,app); this.log("APPLICATION_REGISTERED",actor,app.id); return app; }
  get(actor:Actor,id:string):Application { const app=this.apps.get(id); if(!app) throw new Error("Application not found."); if(actor.role!=="ADMIN"&&app.developerId!==actor.id) throw new Error("Application access denied."); return app; }
  addEvidence(actor:Actor,id:string,type:EvidenceType,locator:string) { const app=this.get(actor,id); if(actor.role!=="DEVELOPER") throw new Error("Developer role required."); if(!/^https:\/\//.test(locator) || /localhost|127\.0\.0\.1|10\.|192\.168\./.test(locator)) throw new Error("Evidence locator must be a public HTTPS URL; verification workers must enforce SSRF policy."); this.log(`EVIDENCE_CLAIMED:${type}`,actor,app.id); }
  transition(actor:Actor,id:string,to:ReviewState,detail?:string) { const app=this.get(actor,id); const adminOnly=["UNDER_REVIEW","APPROVED","PUBLISHED","SUSPENDED","REVOKED"].includes(to); if(adminOnly&&actor.role!=="ADMIN") throw new Error("Admin role required."); if(to==="SUBMITTED"&&actor.role!=="DEVELOPER") throw new Error("Developer role required."); if(!reviewTransitionAllowed(app.state,to)) throw new Error(`Invalid transition ${app.state} -> ${to}.`); app.state=to; this.log(`STATE:${to}`,actor,id,detail); return app; }
  updateCapabilities(actor:Actor,id:string,manifest:unknown) { const app=this.get(actor,id); if(actor.role!=="DEVELOPER") throw new Error("Developer role required."); const valid=validateManifest(manifest); if(!valid.ok) throw new Error(valid.errors.join(" ")); if(app.state==="APPROVED"||app.state==="PUBLISHED") { app.state="CHANGES_REQUIRED"; this.log("CAPABILITY_CHANGE_REVIEW_REQUIRED",actor,id); } app.manifest=valid.value; app.revision++; return app; }
  private log(action:string,actor:Actor,applicationId:string,detail?:string) { this.audit.push({action,actorId:actor.id,applicationId,at:new Date().toISOString(),detail}); }
}
