import { reviewTransitionAllowed, validateManifest, type ApplicationManifestClaim, type EvidenceType, type ReviewState } from "@digiconomy/xperience-contract";
import type { ApplicationRepository } from "./repository.js";
export type Role="DEVELOPER"|"ADMIN"; export interface Actor{id:string;role:Role} export interface Application{id:string;developerId:string;state:ReviewState;manifest:ApplicationManifestClaim;revision:number} export interface AuditEvent{action:string;actorId:string;actorType:Role;applicationId:string;at:string;previousState?:ReviewState;newState?:ReviewState;reason?:string;detail?:string}
export class XperienceService {
 constructor(private readonly repository:ApplicationRepository){}
 private async log(action:string,actor:Actor,applicationId:string,detail?:string,previousState?:ReviewState,newState?:ReviewState){await this.repository.audit({action,actorId:actor.id,actorType:actor.role,applicationId,at:new Date().toISOString(),detail,reason:detail,previousState,newState});}
 async register(actor:Actor,input:unknown){if(actor.role!=="DEVELOPER")throw new Error("Developer role required.");const valid=validateManifest(input);if(!valid.ok)throw new Error(valid.errors.join(" "));const app:Application={id:valid.value.applicationId,developerId:actor.id,state:"DRAFT",manifest:valid.value,revision:1};await this.repository.create(app);await this.log("APPLICATION_REGISTERED",actor,app.id);return app;}
 async get(actor:Actor,id:string){const app=await this.repository.find(id);if(!app)throw new Error("Application not found.");if(actor.role!=="ADMIN"&&app.developerId!==actor.id)throw new Error("Application access denied.");return app;}
 async transition(actor:Actor,id:string,to:ReviewState,reason?:string){const app=await this.get(actor,id),previous=app.state;if(["UNDER_REVIEW","APPROVED","PUBLISHED","SUSPENDED","REVOKED"].includes(to)&&actor.role!=="ADMIN")throw new Error("Admin role required.");if(to==="SUBMITTED"&&actor.role!=="DEVELOPER")throw new Error("Developer role required.");if(!reviewTransitionAllowed(previous,to))throw new Error(`Invalid transition ${previous} -> ${to}.`);app.state=to;await this.repository.save(app);await this.log(`STATE:${to}`,actor,id,reason,previous,to);return app;}
 async updateCapabilities(actor:Actor,id:string,input:unknown){const app=await this.get(actor,id);if(actor.role!=="DEVELOPER")throw new Error("Developer role required.");const valid=validateManifest(input);if(!valid.ok)throw new Error(valid.errors.join(" "));if(app.state==="APPROVED"||app.state==="PUBLISHED")app.state="CHANGES_REQUIRED";app.manifest=valid.value;app.revision++;await this.repository.save(app);await this.log("MANIFEST_REVISED",actor,id);return app;}
 async addEvidence(actor:Actor,id:string,type:EvidenceType,locator:string){const app=await this.get(actor,id);if(actor.role!=="DEVELOPER")throw new Error("Developer role required.");if(!/^https:\/\//.test(locator))throw new Error("Evidence locator must be HTTPS.");await this.log(`EVIDENCE_CLAIMED:${type}`,actor,app.id);}
}
