import { createServer, type IncomingMessage } from "node:http";
import { DevelopmentAuthenticationProvider, productionAuthProvider } from "./auth.js";
import { XperienceService } from "./domain.js";
import { VerificationService } from "./verification.js";
import { prismaClient, closePrisma } from "./prisma.js";
import { PrismaApplicationRepository } from "./repository.js";
const allowed=new Set((process.env.XPERIENCE_CONSOLE_ORIGINS??"http://localhost:5174").split(",")); const service=new XperienceService(new PrismaApplicationRepository(prismaClient())); const auth=process.env.NODE_ENV==="development"?new DevelopmentAuthenticationProvider():productionAuthProvider(); const verification=new VerificationService();
async function body(req:IncomingMessage){let raw="";for await(const chunk of req){raw+=chunk;if(raw.length>100_000)throw new Error("Payload too large.");}return raw?JSON.parse(raw):{};}
function send(res:any,status:number,data:unknown){res.writeHead(status);res.end(JSON.stringify(data));}
const server=createServer(async(req,res)=>{const origin=req.headers.origin;if(origin&&allowed.has(origin))res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Vary","Origin");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Content-Type","application/json");if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Methods":"GET,POST,PATCH","Access-Control-Allow-Headers":"Content-Type,X-Xperience-Dev-Actor"});return res.end();}if(req.url==="/health")return send(res,200,{status:"ok",service:"xperience-api"});const actor=await auth.authenticate(req.headers);if(!actor)return send(res,401,{error:"authentication_required"});try{const path=req.url?.split("?")[0]??"";if(req.method==="POST"&&path==="/v1/applications")return send(res,201,await service.register(actor,await body(req)));const match=path.match(/^\/v1\/applications\/([^/]+)(?:\/(transition|evidence|capabilities))?$/);if(!match)return send(res,404,{error:"not_found"});const [,id,operation]=match;if(req.method==="GET"&&!operation)return send(res,200,await service.get(actor,id));const input=await body(req);if(operation==="transition")return send(res,200,await service.transition(actor,id,input.state,input.reason));if(operation==="capabilities")return send(res,200,await service.updateCapabilities(actor,id,input.manifest));if(operation==="evidence"){await service.addEvidence(actor,id,input.type,input.locator);return send(res,202,await verification.verify({...input,applicationOrigin:(await service.get(actor,id)).manifest.origin}));}return send(res,405,{error:"method_not_allowed"});}catch(error){return send(res,400,{error:error instanceof Error?error.message:"invalid_request"});}});server.listen(Number(process.env.PORT??4100));process.on("SIGTERM",()=>server.close(()=>void closePrisma()));
