export {
  MAX_TARGET_NAME,
  appInstallTarget,
  installableTargetsFor,
  isTargetId,
  parseTargetKey,
  spaceInstallTarget,
  targetKey,
  validateInstallableTarget,
  type AppInstallTarget,
  type InstallTargetIcon,
  type InstallTargetInvalidReason,
  type InstallTargetSource,
  type InstallTargetType,
  type InstallTargetValidation,
  type InstallableTarget,
  type SpaceInstallTarget,
} from "./target.js";
export {
  INSTALLED_TARGETS_KEY,
  confirmInstalledTarget,
  findInstalledTarget,
  readInstalledTargets,
  recordInstalledTarget,
  removeInstalledTarget,
  type InstallationPlatform,
  type InstalledTarget,
  type LaunchEntryState,
} from "./registry.js";
export {
  APP_LAUNCH_ACTION,
  APP_LAUNCH_EXTRA,
  WEB_LAUNCH_PARAM,
  parseAppLaunch,
  resolveInstalledApp,
  routeTargetLaunch,
  webLaunchFromUrl,
  webLaunchPath,
  type AppLaunchResolution,
  type TargetLaunchRoute,
  type WebTargetLaunch,
} from "./launch.js";
export {
  WEB_INSTALL_PARAM,
  appShortcutRequest,
  createAndroidInstallationAdapter,
  createIosInstallationAdapter,
  createUnsupportedInstallationAdapter,
  launchEntryRequest,
  webInstallUrl,
  type AppHomeEntryHost,
  type AppShortcutRequest,
  type ConfirmationGuidance,
  type InstallCapability,
  type InstallMechanism,
  type InstallationPlatformAdapter,
  type LaunchEntryRequest,
  type LaunchEntryResult,
} from "./platform.js";
export {
  INSTALL_ENTRY_CACHE,
  INSTALL_ENTRY_PREFIX,
  browserWebInstallEnvironment,
  createWebInstallationAdapter,
  detectWebBrowser,
  entryManifest,
  entryResourceBase,
  monogramSvg,
  webInstallCapability,
  type DeferredInstallPrompt,
  type WebEntryResource,
  type WebInstallEnvironment,
  type WebInstallationAdapter,
} from "./web-adapter.js";
export {
  installResultMessage,
  installTarget,
  type InstallResult,
  type InstallResultCode,
  type InstallationDeps,
  type SpaceInstallationSteps,
  type SpacePreparationOutcome,
} from "./orchestrator.js";
export {
  isDirectLaunch,
  resolveLaunchMode,
  targetInstallationView,
  type InstallationState,
  type LaunchEntryPresence,
  type LaunchMode,
  type SpaceContinuity,
  type TargetInstallationView,
} from "./state.js";
