import test from "node:test"; import assert from "node:assert/strict";
import { approvedDoesNotAutoPublish, capabilityApprovalIsNotRuntimeAuthorization, isAllowedMessageOrigin, isLifeOSDirectoryEligible, parseExperienceUtterance, parseLifeOSCatalogPayload, reviewTransitionAllowed, validateHandshake, validateManifest } from "../src/index.js";
const manifest={schemaVersion:"1",applicationId:"app.atlas",name:"Atlas",version:"1.0.0",origin:"https://atlas.example.com",productionUrl:"https://atlas.example.com",xperienceUrl:"https://atlas.example.com/xperience",capabilities:["IDENTITY","FILES"]};
test("validates manifest claims and rejects private or secret material",()=>{assert.equal(validateManifest(manifest).ok,true); assert.equal(validateManifest({...manifest,origin:"http://localhost:3000"}).ok,false); assert.equal(validateManifest({...manifest,apiSecret:"nope"}).ok,false); assert.equal(validateManifest({...manifest,capabilities:["FAKE"]}).ok,false)});
test("models explicit review lifecycle",()=>{assert.equal(reviewTransitionAllowed("APPROVED","PUBLISHED"),true);assert.equal(reviewTransitionAllowed("APPROVED","SUBMITTED"),false);assert.equal(reviewTransitionAllowed("PUBLISHED","REVOKED"),true)});
test("capability approval is not runtime authorization and approved does not auto-publish",()=>{assert.equal(capabilityApprovalIsNotRuntimeAuthorization(),true);assert.equal(approvedDoesNotAutoPublish("APPROVED"),true);assert.equal(approvedDoesNotAutoPublish("PUBLISHED"),false)});
test("requires exact public origin in handshake",()=>{const msg={type:"DIGICONOMY_XPERIENCE_HANDSHAKE",protocol:"1",applicationId:"app.atlas",origin:"https://atlas.example.com",nonce:"n"};assert.equal(validateHandshake(msg,{applicationId:"app.atlas",origin:"https://atlas.example.com"}).ok,true);assert.equal(validateHandshake({...msg,origin:"https://evil.example"},{applicationId:"app.atlas",origin:"https://atlas.example.com"}).ok,false);assert.equal(isAllowedMessageOrigin("https://atlas.example.com","https://atlas.example.com"),true);assert.equal(isAllowedMessageOrigin("https://evil.example","https://atlas.example.com"),false)});
test("LifeOS catalog eligibility and parse",()=>{const ok={applicationId:"mr.fundzman",name:"Mr FundzMan",version:"1.0.0",origin:"https://mr-fundzman.lifeos.example",productionUrl:"https://mr-fundzman.lifeos.example/app",xperienceUrl:"https://mr-fundzman.lifeos.example/x",capabilities:["COMMERCE"],visibility:"PUBLIC",publicationState:"PUBLISHED"};assert.equal(isLifeOSDirectoryEligible(ok),true);assert.equal(isLifeOSDirectoryEligible({...ok,publicationState:"DRAFT"}),false);assert.equal(parseLifeOSCatalogPayload({applications:[ok, {...ok,applicationId:"x",visibility:"PRIVATE"}]}).length,2)});
test("routes experience utterances",()=>{assert.deepEqual(parseExperienceUtterance("Open Mr FundzMan"),{kind:"open",query:"mr fundzman"});assert.deepEqual(parseExperienceUtterance("Add LifeOS to my Experience"),{kind:"start_experience",query:"lifeos"});assert.deepEqual(parseExperienceUtterance("Find finance apps"),{kind:"category",category:"Finance"});assert.deepEqual(parseExperienceUtterance("Show my applications"),{kind:"show_experience"})});
